# Generated by Django 5.0 on 2023-12-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('outdoor', models.BooleanField(default=False)),
                ('players', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('M', 'Motor'), ('B', 'Ball Sport'), ('W', 'Water Sport'), ('A', 'Air Sport'), ('K', 'Bikes'), ('T', 'Athletics')], max_length=1)),
            ],
        ),
    ]
