# Generated by Django 5.0 on 2023-12-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='origin',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
