# Generated by Django 5.0 on 2023-12-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_rename_outdoor_sport_is_outdoor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='is_outdoor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
