# Generated by Django 5.0 on 2023-12-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('continent', models.TextField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'worldcountries',
                'managed': True,
            },
        ),
    ]
